#!/usr/bin/env python3

from subprocess     import Popen
#
from os.path        import join, dirname, realpath, isfile
from flask          import Flask , send_from_directory


Popen (
    ["/usr/bin/open", "-W", "-n", "-a", "/Applications/Internet/Opera.app", "http://0.0.0.0:8080/"]
)


SCRIPT_DIR          = dirname( realpath(__file__) )
app                 = Flask(__name__)
 

#INDEX
@app.route('/', methods=['GET'])
def index():
    return send_from_directory('.', 'index.html')


#SERVE
@app.route('/<path:loc>', methods=['GET'])
def serve_static_files(loc):
    if not isfile( join( SCRIPT_DIR, loc) ):
        loc = join( loc, 'home.html' )
    return send_from_directory(SCRIPT_DIR, loc)


# =================================================================== #
#                               MAIN                                  #
# =================================================================== #
if __name__ == '__main__':
    app.run(host='0.0.0.0',port=8080)